### ISSUE TITLE
When placing the obsidian boat, it always faces south [Issue]

### ISSUE THREAD

**Issue by modtraf** [nanite/TheObsidianBoat#12]
### Minecraft Version

1.20.1

### Modloader

Fabric - 0.14.24

### Mod version

3.0.2

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

no logs relevant

### Steps to reproduce the issue

Place an obsidian boat on seemingly any surface, it will face south. Can be lava, water, or some solid block.

### Description of the issue you are having

Here's a screenshot of expected behavior on the left, and actual behavior on the right. I stood on the central block and placed a few boats in a circle around me. A standard boat (in this case represented by the crimson boat from the Extra Boats mod) faces in whatever direction the player is facing when placing the boat. As currently written, TheObsidianBoat always faces south.
![temp](https://github.com/nanite/TheObsidianBoat/assets/158414589/847c1493-4722-48dd-89b5-28cfaa9242fe)

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Fixed in latest commit. It's building now, then should appear on CurseForge sometime after

**Comment by modtraf** [comment]
Fantastic, thank you!
