### ISSUE TITLE
[Feature Request] Is it possible to fix "placed boats face south" in specifically 1.20.1?

### ISSUE THREAD

**Issue by modtraf** [nanite/TheObsidianBoat#13]
### Feature Description

Would it be possible to fix the "boats face south" issue in a version of your mod that is compatible with minecraft 1.20.1? I'm referencing this: https://github.com/nanite/TheObsidianBoat/issues/12

I know some mod authors make versions that are compatible for anything past 1.20, such as "1.20.x" or similar. Is that possible in however you compile things? Apologies if what I'm asking would be horrifically time consuming, I have no frame of reference for me to understand how difficult or easy this request would be.

Thank you for taking the time to read this, it's rare in my experience to find such a responsive developer. Nicely done!

[Extra Context: I'd like to be able to upgrade to 1.20.4, but the manhunt modpack I made requires origins, and origins (and a few other mods) haven't upgraded to 1.20.4 quite yet. It's a "phantom manhunt", so... I'm extremely stuck with 1.20.1. I don't think the boat placement thing is enough for us not to use it as-is, but I can imagine situations where someone could sneak in an axe crit while the runner was trying to run north, but had to sit and turn the boat around since it placed facing south.]

**Comment by UnRealDinnerbone** [comment]
Back ported the Fix to 1.20.1 same as before. Building now, then Curse forge after
