### ISSUE TITLE
Take Damage When Using Boat in Lava

### ISSUE THREAD

**Issue by EchoWhiskeyZero** [nanite/TheObsidianBoat#2]
### Mod version

ObsidianBoat-1.2.0-build.9+mc1.18.jar

### Forge mod loader version

39.0.43

### Repeatable?

- [X] Yes

### Link to log files

N/A

### Steps to reproduce the issue

1. Put boat in lava (in overworld or nether)
2. Get in boat
3. Die from damage

### Description of the issue you are having

I love the concept of this mod and hope to get it to work! However, I die from damage when in obsidian boat that is in lava. Am I doing something wrong or is this a bug?

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Fixed new version should be on curseforge soon
