### ISSUE TITLE
[Feature Request] Make it easier to retrieve obsidian boat from lava

### ISSUE THREAD

**Issue by 0DeltaWaves** [nanite/TheObsidianBoat#4]
### Feature Description

Currently it's difficult to get the boat back once it's placed on lava. Breaking the boat usually leads to the item burning and being destroyed. A possible solution is to allow players to crouch and right click the boat to retrieve it without breaking it, or at least have the item form be fireproof so it can float in lava like netherite gear.

Thanks for your consideration

**Comment by UnRealDinnerbone** [comment]
Push new version for 1.18.2 that makes the boat item not burn like netherrite
