### ISSUE TITLE
please make a fabric version. 

### ISSUE THREAD

**Issue by TakeTwo4444** [nanite/TheObsidianBoat#5]
### Feature Description

I am making a modpack and most mods are with fabric, so I can't use this, but I want to.

**Comment by DTX3** [comment]
+1 please

**Comment by allanonmage** [comment]
also +1.  Seems there is no competing option for a nether boat at all, so you can keep being the exclusive option for nether boats.

**Comment by UnRealDinnerbone** [comment]
done
