### ISSUE TITLE
Minecraft doesn't open with the mod installed on fabric version 1.20.1

### ISSUE THREAD

**Issue by Thanatosxg** [nanite/TheObsidianBoat#7]
### Minecraft Version

1.20.1

### Modloader

Fabric 0.14.21

### Mod version

3.0.0 mc 1.20.1 fabric

### Latest version?

- [X] Yes

### Repeatable?

- [X] Yes

### Link to log files

[crash-2023-07-27_13.23.33-client.txt](https://github.com/nanite/TheObsidianBoat/files/12185745/crash-2023-07-27_13.23.33-client.txt)

### Steps to reproduce the issue

On the initialization of minecraft

### Description of the issue you are having

I click on PLAY and the game go back to the launcher and the error is The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'obsidianboat'!

### Information

- [X] I have provided as much information as possible

**Comment by UnRealDinnerbone** [comment]
Install https://legacy.curseforge.com/minecraft/mc-mods/trenzalore 
Publishing new version that errors correctly
